spring:
    datasource:
        url: jdbc:mysql://localhost:3306/study?useUnicode=true&useSSL=false&&characterEncoding=UTF-8
        username: root
        password: root
        driverClassName: com.mysql.cj.jdbc.Driver
        tomcat:
            connection-properties: useUnicode=true;characterEncoding=utf-8;