spring:
    datasource:
        url: jdbc:mysql://localhost:3306/study?useUnicode=true&useSSL=false&&characterEncoding=UTF-8
        username: root
        password: password
        driverClassName: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
mybatis-plus:
    mapper-locations:
